'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4918
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class JikJikoo
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JikJikoo.JikJikoo", GetType(JikJikoo).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Statuses Completed.
        '''</summary>
        Friend Shared ReadOnly Property AddStatusEnd() As String
            Get
                Return ResourceManager.GetString("AddStatusEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adding Statuses ....
        '''</summary>
        Friend Shared ReadOnly Property AddStatusStart() As String
            Get
                Return ResourceManager.GetString("AddStatusStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cashing Images Completed.
        '''</summary>
        Friend Shared ReadOnly Property CachingImageEnd() As String
            Get
                Return ResourceManager.GetString("CachingImageEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cashing Images ....
        '''</summary>
        Friend Shared ReadOnly Property CashingImageStart() As String
            Get
                Return ResourceManager.GetString("CashingImageStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send Message.
        '''</summary>
        Friend Shared ReadOnly Property DirectButton() As String
            Get
                Return ResourceManager.GetString("DirectButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download Data Completed.
        '''</summary>
        Friend Shared ReadOnly Property DownloadDataEnd() As String
            Get
                Return ResourceManager.GetString("DownloadDataEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading Data ....
        '''</summary>
        Friend Shared ReadOnly Property DownloadDataStart() As String
            Get
                Return ResourceManager.GetString("DownloadDataStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Login.
        '''</summary>
        Friend Shared ReadOnly Property login() As String
            Get
                Return ResourceManager.GetString("login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username not found.
        '''</summary>
        Friend Shared ReadOnly Property LoginError() As String
            Get
                Return ResourceManager.GetString("LoginError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;logout.
        '''</summary>
        Friend Shared ReadOnly Property logout() As String
            Get
                Return ResourceManager.GetString("logout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} New Update(s).
        '''</summary>
        Friend Shared ReadOnly Property NewUpdate() As String
            Get
                Return ResourceManager.GetString("NewUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Reply.
        '''</summary>
        Friend Shared ReadOnly Property ReplyButton() As String
            Get
                Return ResourceManager.GetString("ReplyButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must complete authentication.
        '''</summary>
        Friend Shared ReadOnly Property VeryfingError() As String
            Get
                Return ResourceManager.GetString("VeryfingError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
